// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Jkm4f3DxnEq9wY7e_Lrwa47WwJSXLUM',
    appId: '1:908984739654:web:17e8e5500eb09901e6e747',
    messagingSenderId: '908984739654',
    projectId: 'passwordapp-e06d5',
    authDomain: 'passwordapp-e06d5.firebaseapp.com',
    storageBucket: 'passwordapp-e06d5.appspot.com',
    measurementId: 'G-W05RGG2ZR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVpNtQnR0Y3RAtf1vu4bDicPw89H5qqQ',
    appId: '1:908984739654:android:e466bcde10e98616e6e747',
    messagingSenderId: '908984739654',
    projectId: 'passwordapp-e06d5',
    storageBucket: 'passwordapp-e06d5.appspot.com',
  );
}
